<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPm4ystx\EccubeProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPm4ystx/EccubeProdProjectContainer.php') {
    touch(__DIR__.'/ContainerPm4ystx.legacy');

    return;
}

if (!\class_exists(EccubeProdProjectContainer::class, false)) {
    \class_alias(\ContainerPm4ystx\EccubeProdProjectContainer::class, EccubeProdProjectContainer::class, false);
}

return new \ContainerPm4ystx\EccubeProdProjectContainer([
    'container.build_hash' => 'Pm4ystx',
    'container.build_id' => '2421be41',
    'container.build_time' => 1625212114,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPm4ystx');
